export const SHIPROCKET_STATUS_CODE_LABEL: Record<number, string> = {
  1: 'New',
  2: 'Invoiced',
  3: 'Ready To Ship',
  4: 'Pickup Scheduled',
  5: 'Canceled',
  6: 'Shipped',
  7: 'Delivered',
  8: 'ePayment Failed',
  9: 'Returned',
  10: 'Unmapped',
  11: 'Unfulfillable',
  12: 'Pickup Queue',
  13: 'Pickup Rescheduled',
  14: 'Pickup Error',
  15: 'RTO Initiated',
  16: 'RTO Delivered',
  17: 'RTO Acknowledged',
  18: 'Cancellation Requested',
  19: 'Out for Delivery',
  20: 'In Transit',
  21: 'Return Pending',
  22: 'Return Initiated',
  23: 'Return Pickup Queued',
  24: 'Return Pickup Error',
  25: 'Return In Transit',
  26: 'Return Delivered',
  27: 'Pickup Booked',
  28: 'Return Pickup Generated',
  29: 'Return Cancellation Requested',
  30: 'Return Pickup Cancelled',
  31: 'Return Pickup Rescheduled',
  32: 'Return Picked Up',
  33: 'Lost',
  34: 'Out For Pickup',
  35: 'Pickup Exception',
  36: 'Undelivered',
  37: 'Delivery Delayed',
  38: 'Partial Delivered',
  39: 'Destroyed',
  40: 'Damaged',
  41: 'Fulfilled',
  42: 'Archived',
  43: 'Reached Destination Hub',
  44: 'Misrouted',
  45: 'RTO_OFD',
  46: 'RTO_NDR',
  47: 'Return Out For Pickup',
  48: 'Return Out For Delivery',
  49: 'Return Pickup Exception',
  50: 'Return Undelivered',
  51: 'Picked Up',
  52: 'Self Fulfilled',
  53: 'Disposed Off',
  54: 'Canceled before Dispatched',
  55: 'RTO In-Transit',
  57: 'QC Failed',
  58: 'Reached Warehouse',
  59: 'Custom Cleared',
  60: 'In Flight',
  61: 'Handover to Courier',
  62: 'Booked',
  64: 'In Transit Overseas',
  65: 'Connection Aligned',
  66: 'Reached Overseas Warehouse',
  67: 'Custom Cleared Overseas',
  68: 'RETURN ACKNOWLEGED',
  69: 'Box Packing',
  70: 'Pickup Booked',
  71: 'DARKSTORE SCHEDULED',
  72: 'Allocation in Progress',
  73: 'FC Allocated',
  74: 'Picklist Generated',
  75: 'Ready to Pack',
  76: 'Packed',
  80: 'FC MANIFEST GENERATED',
  81: 'PROCESSED AT WAREHOUSE',
  82: 'PACKED EXCEPTION',
  83: 'HANDOVER EXCEPTION',
  87: 'RTO_LOCK',
  88: 'UNTRACEABLE',
  89: 'ISSUE_RELATED_TO_THE_RECIPIENT',
  90: 'REACHED_BACK_AT_SELLER_CITY',
};

export function isNumericOnly(value: unknown): boolean {
  if (value === null || value === undefined) return false;
  const s = String(value).trim();
  return !!s && /^\d+$/.test(s);
}

export function shiprocketStatusCodeToLabel(value: unknown): string | null {
  if (!isNumericOnly(value)) return null;
  const code = Number(String(value).trim());
  if (!Number.isFinite(code)) return null;
  return SHIPROCKET_STATUS_CODE_LABEL[code] || null;
}
